version: '3.7'
services:
  db:
    image: mysql:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
    environment:
      - MYSQL_DATABASE=swarm
      - MYSQL_ROOT_PASSWORD=EYmnKf62B2ULwbEQuLL3
      - MYSQL_USER=nica
      - MYSQL_PASSWORD=EA43VfjN5JuDvj3do1Dm
    volumes: 
      - database:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - reddocker
        #- reddb

  wordpress:
    image: wordpress:5.2.2-fpm-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
    depends_on:
      - db
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=nica
      - WORDPRESS_DB_PASSWORD=EA43VfjN5JuDvj3do1Dm
      - WORDPRESS_DB_NAME=swarm
    volumes:
      - web:/var/www/html
    networks:
      - reddocker
        # - reddb

  nginx:
    image: nginx:1.17.3-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    depends_on:
      - wordpress
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web:/var/www/html
      - nginx:/etc/nginx
      - ./swarm.conf:/etc/nginx/conf.d/default.conf
      - certificado:/etc/letsencrypt
      - ./options-ssl-nginx.conf:/etc/nginx/conf.d/options-ssl-nginx.conf
    networks:
      - reddocker

  htpps:
    image: certbot/certbot
    deploy:
      replicas: 1
      restart_policy:
         condition: on-failure
      placement:
         constraints:
         - node.role == manager
    volumes:
     - certificado:/etc/letsencrypt
     - ssl:/var/lib/letsencrypt
     - web:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email tetrix@riseup.net --agree-tos --no-eff-email --force-renewal --staging -d swarm.pytrix.me -d www.swarm.pytrix.me
     
volumes:
  certificado:
  ssl:
  web:
  rpi-mysql:
  nginx:
  database:

networks:
  reddocker:
    driver: overlay
    #reddb:
    #driver: overlay
