version: '3.7'
services:    
  htpps:
   image: certbot/certbot
   deploy:
     replicas: 1
     restart_policy:
        condition: on-failure
     placement:
        constraints:
         - node.role == manager
   volumes:
    - certificado:/etc/letsencrypt
    - ssl:/var/lib/letsencrypt
    - web:/var/www/html
   command: certonly --webroot --webroot-path=/var/www/html --email tetrix@riseup.net --agree-tos --no-eff-email --force-renewal --staging -d swarm.pytrix.me -d www.swarm.pytrix.me

volumes:
  certificado:
  ssl:
  web:

